/**
 * Single source of truth for everything that is "about Md Azmal" rather than
 * "about the site". Change copy here, not inside components.
 */

export const site = {
  /** Canonical origin. Used for absolute URLs in <link rel="canonical"> and OG tags. */
  url: 'https://md-azmal.github.io',

  name: 'Md Azmal',
  /** Short form used in the nav pill. */
  shortName: 'Azmal',
  role: 'Tech Lead, Agentic AI CoE',
  company: 'Tech Mahindra',
  location: 'Bhubaneswar, India',
  email: 'azmalmd12@gmail.com',

  title: 'Md Azmal — Tech Lead, Agentic AI',
  description:
    'Tech Lead in the Agentic AI CoE at Tech Mahindra. Shipping agentic systems to production — front to back. Previously IMESH (service mesh, Kubernetes) and cybersecurity research at IIT Kanpur.',

  /**
   * 1200x630 social card, generated by `pnpm og`. A JPEG, not a PNG: WhatsApp
   * drops the preview image above roughly 300 kB, and the PNG sat right at it.
   */
  ogImage: '/og.jpg',
  ogImageAlt: 'Md Azmal, Tech Lead in the Agentic AI CoE at Tech Mahindra',
  avatar: '/avatar.png',
  /** Open Graph locale, and the language named in structured data. */
  locale: 'en_US',
  /** X handle, for twitter:site / twitter:creator. */
  twitter: '@MDAzMaL11',
  keywords: ['Md Azmal', 'Agentic AI', 'AI agents', 'Tech Lead', 'LLM', 'Tech Mahindra'],

  links: {
    github: 'https://github.com/MD-AZMAL',
    linkedin: 'https://www.linkedin.com/in/md-azmal11',
    x: 'https://twitter.com/MDAzMaL11',
  },
} as const

export const nav = [
  { label: 'Home', to: '/' },
  { label: 'Projects', to: '/projects' },
  { label: 'Blog', to: '/blog' },
  { label: 'Contact', to: '/#contact' },
] as const

/* ------------------------------------------------------------------ *
 * Home page copy
 * ------------------------------------------------------------------ */

export const home = {
  /** The oversized word next to the profile card. */
  display: 'Agentic',
  displaySub: 'Designing the systems that let models do real work in production.',

  intro: 'Tech Lead in the Agentic AI CoE at Tech Mahindra.',

  /** Rotating text on the spinning badge. */
  badgeText: 'AGENTIC AI - TECH LEAD - ',

  featured: {
    eyebrow: 'Featured - Tech Mahindra',
    title: 'Agentic payment assistance, live on AWS Marketplace',
    body: 'An agentic collections and payment-assistance solution built in the Agentic AI CoE, listed publicly on AWS Marketplace.',
    href: '/projects/agentic-payment-assistance',
  },

  stats: {
    /** `suffix` is appended to the counted number, e.g. "5+". */
    primary: { value: 5, suffix: '+', label: 'Years shipping software' },
    /** The one orange fill in the hero. */
    secondary: { value: 3, suffix: '', label: 'Teams and startups built with' },
  },

  /** Shown as pills beside the sphere in the hero's wide card. */
  builtWith: [
    'TypeScript',
    'Python',
    'AWS',
    'AgentCore',
    'AI SDK',
    'LangGraph',
    'Strands SDK',
    'ADK',
    'A2A',
    'MCP',
    'React',
    'PyTorch',
    'Fine-tuning',
    'Go',
    'Kubernetes',
  ],

  marquee: [
    'Agentic AI',
    'LLM fine-tuning',
    'Service mesh',
    'Kubernetes',
    'Blockchain',
    'Security',
    'System design',
    'Product design',
  ],

  cta: {
    title: "Building something agentic? Let's compare notes.",
    body: 'Open to conversations about agent runtimes, evaluation, and getting AI systems past the demo stage. Based in Bhubaneswar, working with teams anywhere.',
  },
} as const

/* ------------------------------------------------------------------ *
 * Topic taxonomy — shared by the blog and the project archive
 * ------------------------------------------------------------------ */

export type TopicId = 'ai' | 'security' | 'blockchain' | 'craft' | 'platform'

export const topics: { id: TopicId; label: string; hint: string; tone: string }[] = [
  { id: 'ai', label: 'Agentic AI', hint: 'agents - runtimes - evals', tone: 'deep' },
  { id: 'security', label: 'Security', hint: 'honeypots - steganography', tone: '' },
  { id: 'blockchain', label: 'Blockchain', hint: 'ledgers - hyperledger fabric', tone: 'deep' },
  { id: 'platform', label: 'Platform', hint: 'kubernetes - service mesh', tone: '' },
  { id: 'craft', label: 'Craft', hint: 'generative art - tooling', tone: 'deep' },
]

export const topicLabel = (id: string): string =>
  topics.find((t) => t.id === id)?.label ?? id

